[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["jiho7407 <mmm7407@yonsei.ac.kr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
